version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres_db_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_test_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: pushc/devops-for-developers-project-74:latest
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/app
    environment:
      NODE_ENV: test
      DATABASE_HOST: db
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    command: npm test

volumes:
  postgres_test_data:
